apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
  labels:
    app: daemonset
spec:
  selector:
    matchLabels:
      name: daemonset
  template:
    metadata:
      labels:
        name: daemonset
    spec:
      tolerations:
      - key: key
        effect: NoSchedule
      containers:
      - name: ubuntu
        image: ubuntu:latest
