apiVersion: v1
kind: Secret
metadata:
  name: secret-creds
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis-pod
      image: redis
      volumeMounts:
          # name must match the volume name below
         - name: secret-creds
           mountPath: /app-creds
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-creds
      secret:
        secretName: secret-creds
